[options]
packages = find:
include_package_data = True

[options.package_data]
* = launch/*.py, urdf/*.xacro, urdf/*.urdf, rviz/*.rviz, paths/*.txt

[options.data_files]
share/kinematics_assignment/urdf =
    urdf/SCARA.urdf


[develop]                     # ← used when you pass --symlink-install
script_dir = $base/lib/kinematics_assignment

[install]                     # ← used for a normal (non-symlink) install
install_scripts = $base/lib/kinematics_assignment
