[package.build.backend]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-build-ros"
version = "*"

[package.build.config]
extra-input-globs = [
  "rviz/*",
  "launch/*.py",
  "kinematics_assignment/*.py",
  "urdf/*",
]

[package.host-dependencies]
ros2-distro-mutex = ">=0.13,<0.14"

[package.build-dependencies]
ros2-distro-mutex = ">=0.13,<0.14"

[package.run-dependencies]
ros2-distro-mutex = ">=0.13,<0.14"